version: "3"

services:
    backend:
        build:
            context: ./nodejs
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_USER=<postgres_user>
            - POSTGRES_PASSWORD=<postgres_password>
            - POSTGRES_DB=<postgres_database>
        depends_on:
            - db

    frontend:
        build:
            context: ./reactjs
        ports:
            - "80:80"

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD:
            POSTGRES_DB: petstore
