version: "3"

services:
    backend:
        build:
            context: ./nodejs
        ports:
            - "127.0.0.1:8888:8888"
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=petstore
        depends_on:
            - db

    frontend:
        build:
            context: ./reactjs
        ports:
            - "127.0.0.1:3000:3000"

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD:
            POSTGRES_DB: petstore
